"""initial_migration

Revision ID: e39637576048
Revises: 
Create Date: 2026-07-09 09:22:01.612370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e39637576048'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code ~ '^[A-Z0-9-]+$'", name='building_code_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildings_code'), 'buildings', ['code'], unique=True)
    op.create_index(op.f('ix_buildings_name'), 'buildings', ['name'], unique=True)
    op.create_table('employees',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('employee_code', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=False),
    sa.Column('designation', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('reporting_manager_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'on_leave', 'exited')", name='employee_status_check'),
    sa.ForeignKeyConstraint(['reporting_manager_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_employee_full_name_trgm', 'employees', [sa.literal_column("(first_name || ' ' || last_name)")], unique=False, postgresql_using='gin', postgresql_ops={'(first_name || \' \' || last_name)': 'gin_trgm_ops'})
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    op.create_index(op.f('ix_employees_status'), 'employees', ['status'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('client_name', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'on_hold', 'closed')", name='project_status_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_name_trgm', 'projects', [sa.literal_column('name')], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_projects_project_code'), 'projects', ['project_code'], unique=True)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('employee_projects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('role_on_project', sa.String(length=80), nullable=False),
    sa.Column('allocation_percent', sa.SmallInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('allocation_percent BETWEEN 1 AND 100', name='employee_project_allocation_check'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'project_id', 'start_date', name='uq_employee_project_start')
    )
    op.create_index('ix_employee_projects_active_employee', 'employee_projects', ['employee_id'], unique=False, postgresql_where=sa.text('end_date IS NULL'))
    op.create_index(op.f('ix_employee_projects_employee_id'), 'employee_projects', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_projects_project_id'), 'employee_projects', ['project_id'], unique=False)
    op.create_table('floors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('building_id', sa.BigInteger(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'floor_number', name='uq_building_floor')
    )
    op.create_index(op.f('ix_floors_building_id'), 'floors', ['building_id'], unique=False)
    op.create_table('seats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('floor_id', sa.BigInteger(), nullable=False),
    sa.Column('seat_code', sa.String(length=30), nullable=False),
    sa.Column('seat_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('available', 'occupied', 'reserved', 'maintenance')", name='seat_status_check'),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('floor_id', 'seat_code', name='uq_floor_seat_code')
    )
    op.create_index(op.f('ix_seats_floor_id'), 'seats', ['floor_id'], unique=False)
    op.create_index(op.f('ix_seats_status'), 'seats', ['status'], unique=False)
    op.create_table('seat_assignments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('seat_id', sa.BigInteger(), nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seat_assignments_employee_id'), 'seat_assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_seat_assignments_released_at'), 'seat_assignments', ['released_at'], unique=False)
    op.create_index(op.f('ix_seat_assignments_seat_id'), 'seat_assignments', ['seat_id'], unique=False)
    op.create_index('uq_active_employee_seat', 'seat_assignments', ['employee_id'], unique=True, postgresql_where=sa.text('released_at IS NULL'))
    op.create_index('uq_active_seat_occupant', 'seat_assignments', ['seat_id'], unique=True, postgresql_where=sa.text('released_at IS NULL'))
    op.create_table('seat_release_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('seat_assignment_id', sa.BigInteger(), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("reason IN ('resigned', 'relocated', 'project_change', 'other')", name='seat_release_reason_check'),
    sa.ForeignKeyConstraint(['released_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seat_assignment_id'], ['seat_assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seat_release_logs_released_at'), 'seat_release_logs', ['released_at'], unique=False)
    op.create_index(op.f('ix_seat_release_logs_seat_assignment_id'), 'seat_release_logs', ['seat_assignment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seat_release_logs_seat_assignment_id'), table_name='seat_release_logs')
    op.drop_index(op.f('ix_seat_release_logs_released_at'), table_name='seat_release_logs')
    op.drop_table('seat_release_logs')
    op.drop_index('uq_active_seat_occupant', table_name='seat_assignments', postgresql_where=sa.text('released_at IS NULL'))
    op.drop_index('uq_active_employee_seat', table_name='seat_assignments', postgresql_where=sa.text('released_at IS NULL'))
    op.drop_index(op.f('ix_seat_assignments_seat_id'), table_name='seat_assignments')
    op.drop_index(op.f('ix_seat_assignments_released_at'), table_name='seat_assignments')
    op.drop_index(op.f('ix_seat_assignments_employee_id'), table_name='seat_assignments')
    op.drop_table('seat_assignments')
    op.drop_index(op.f('ix_seats_status'), table_name='seats')
    op.drop_index(op.f('ix_seats_floor_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_index(op.f('ix_floors_building_id'), table_name='floors')
    op.drop_table('floors')
    op.drop_index(op.f('ix_employee_projects_project_id'), table_name='employee_projects')
    op.drop_index(op.f('ix_employee_projects_employee_id'), table_name='employee_projects')
    op.drop_index('ix_employee_projects_active_employee', table_name='employee_projects', postgresql_where=sa.text('end_date IS NULL'))
    op.drop_table('employee_projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_code'), table_name='projects')
    op.drop_index('ix_project_name_trgm', table_name='projects', postgresql_using='gin')
    op.drop_table('projects')
    op.drop_index(op.f('ix_employees_status'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_department'), table_name='employees')
    op.drop_index('ix_employee_full_name_trgm', table_name='employees', postgresql_using='gin')
    op.drop_table('employees')
    op.drop_index(op.f('ix_buildings_name'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_code'), table_name='buildings')
    op.drop_table('buildings')
    # ### end Alembic commands ###
